title: Slowburn
description: Movie reviews and culture
url: https://slowburn.mov

collections:
  reviews:
    output: true
    permalink: /reviews/:slug

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:slug/
  - scope:
      path: ""
      type: "reviews"
    values:
      layout: "post"
      type: "Review"