title: Slowburn
description: Movie reviews, interviews, and news
url: https://slowburn.mov

collections:
  reviews:
    output: true
    permalink: /reviews/:title-:year

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "reviews"
    values:
      layout: "post"
      type: "Review"